* Schematics Aliases *

.ALIASES
U_DSTM-X          DSTM-X(PWR=$G_DPWR GND=$G_DGND OUT0=$N_0001 )
U_DSTM-Y          DSTM-Y(PWR=$G_DPWR GND=$G_DGND OUT0=$N_0002 )
X_U1A           U1A(A=$N_0001 B=$N_0002 Y=DIFFERENCE PWR=$G_DPWR GND=$G_DGND )
X_U3A           U3A(A=$N_0001 Y=$N_0003 PWR=$G_DPWR GND=$G_DGND )
X_U2A           U2A(A=$N_0003 B=$N_0002 Y=BORROW PWR=$G_DPWR GND=$G_DGND )
_    _(DIFFERENCE=DIFFERENCE)
_    _(BORROW=BORROW)
_    _($G_DPWR=$G_DPWR)
_    _($G_DGND=$G_DGND)
.ENDALIASES

